version: "3.7"
services:
  machine-learn:
    build:
      context: machine-learn
      target: development
    privileged: true
    env_file:
      - .env
    ports:
      - "9001:8888"
    networks: 
      - app_net

networks:
    app_net:
        external: true