version: "3.7"
services:
  machine-learn:
    build:
      context: machine-learn
      target: development
    command: sleep infinity 
    privileged: true
    env_file:
      - .env
    ports:
      - "8080"
    networks: 
      - app_net

networks:
    app_net:
        external: true